In [1]:
import pandas as pd

In [2]:
path = r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB" 
df = pd.read_csv(path)

In [3]:
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [5]:
x=df.drop('price',axis=1)
y=df['price']
print('shape of X = ',x.shape)
print('shape of y= ',y.shape)

shape of X =  (7120, 107)
shape of y=  (7120,)


In [7]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test= train_test_split(x,y ,test_size=0.2,random_state=51)

In [17]:
print('x_train shape =',x_train.shape)
print('y_train shape =',y_train.shape)
print('x_test shape =',x_test.shape)
print('y_test shape =',y_test.shape)

x_train shape = (5696, 107)
y_train shape = (5696,)
x_test shape = (1424, 107)
y_test shape = (1424,)


In [18]:
from sklearn.preprocessing import StandardScaler

In [26]:
sc=StandardScaler()
sc.fit(x_train,x_test)
x_train=sc.transform(x_train)
x_test=sc.transform(x_test)


In [31]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [37]:
#lr.coef_


In [38]:
x_train

array([[ 3.0245515 ,  0.55008644,  1.33396246, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -2.0427027 , -0.60737352, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597,  0.55008644, -0.36873754, ..., -0.05630391,
        -0.05630391, -0.05138463],
       ...,
       [-0.44274597,  0.55008644, -0.49772996, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597,  0.55008644, -0.62414253, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -0.74630813, -0.6009239 , ..., -0.05630391,
        -0.05630391, -0.05138463]])

In [41]:
lr.predict([x_test[0, : ]])

array([76.90661876])

In [42]:
lr.predict(x_test)

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [43]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [44]:
lr.score(x_test,y_test)

0.7903837092682253

In [46]:
# Root Mean Square Error

y_pred=lr.predict(x_test)
y_pred

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [47]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [51]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [52]:
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print('mse=',mse)
print('rmse=',rmse)


mse= 4211.806905823326
rmse= 64.89843531105605
